/**
 * Builds a throwaway Chromium MV3 extension used only to measure whether a
 * provider is reachable from a real privileged extension context.
 *
 * The extension is generated into a temp directory at run time and is never
 * committed. Its only capability is host access to the provider origins under
 * test — the same grant a real SpectreMail extension would need.
 */

import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

const MANIFEST = (version, origins) =>
  JSON.stringify(
    {
      manifest_version: 3,
      name: `SpectreMail M0 spike probe (${version})`,
      version: "0.0.1",
      description:
        "Disposable fixture that measures provider reachability from an extension context. Generated by the M0 spike; not shipped.",
      permissions: ["storage"],
      host_permissions: origins,
      background: { service_worker: "sw.js", type: "module" },
      options_page: "probe.html",
    },
    null,
    2,
  );

const SERVICE_WORKER = `
// Minimal worker. Its presence is what grants the extension cross-origin fetch.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()));
`;

const PROBE_PAGE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>SpectreMail M0 extension probe</title>
  </head>
  <body>
    <p>Disposable extension probe page generated by the M0 spike.</p>
    <script type="module" src="probe.js"></script>
  </body>
</html>
`;

/**
 * Chrome match patterns require a path component.
 *
 * `https://api.mail.tm` is accepted into the manifest but grants NO access —
 * the extension then fails every cross-origin fetch with an opaque
 * "Failed to fetch". `https://api.mail.tm/*` works. This was measured in this
 * spike, not assumed, so the fixture must not reintroduce the broken form.
 */
export function toMatchPatterns(origins) {
  return origins.map((origin) => `${origin.replace(/\/+$/, "")}/*`);
}

export async function buildExtensionFixture({ origins, version }) {
  const hostPermissions = toMatchPatterns(origins);
  const manifestText = MANIFEST(version, hostPermissions);
  const dir = await mkdtemp(path.join(tmpdir(), "spectre-spike-ext-"));
  await writeFile(path.join(dir, "manifest.json"), manifestText, "utf8");
  await writeFile(path.join(dir, "sw.js"), SERVICE_WORKER, "utf8");
  await writeFile(path.join(dir, "probe.html"), PROBE_PAGE, "utf8");
  // Intentionally empty: the page exists to give the extension origin a
  // document in which to run fetches.
  await writeFile(path.join(dir, "probe.js"), "export {};\n", "utf8");
  return { dir, manifest: JSON.parse(manifestText) };
}
